# Generated by Django 4.2.1 on 2024-12-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_specialist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialist',
            options={'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='specialist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialists', to='users.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='specialists/photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='dop_info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
    ]
