# Generated by Django 4.2.1 on 2024-12-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_specialist_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='experience',
            field=models.CharField(max_length=25, verbose_name='Стаж работы'),
        ),
    ]
