# Generated by Django 4.2.1 on 2024-12-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка'),
        ),
    ]
