# Generated by Django 4.2.1 on 2025-01-01 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='users.service', verbose_name='Услуга')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Связь специалиста и услуги',
                'verbose_name_plural': 'Связи специалистов и услуг',
                'unique_together': {('specialist', 'service')},
            },
        ),
    ]
