# Generated by Django 4.2.1 on 2025-01-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(help_text='Пример: ул. (Название улицы или проспекта(пр.)), д. (Номер дома), Город', max_length=255, verbose_name='Адрес'),
        ),
    ]
