# Generated by Django 4.2.1 on 2025-01-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_address_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=100, unique=True, verbose_name='Данные для связи')),
                ('person', models.CharField(max_length=100, verbose_name='Человек для связи')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(help_text='Пример: ул. (Название улицы или проспекта(пр.)), (Номер дома), Город\n', max_length=255, verbose_name='Адрес'),
        ),
    ]
