# Generated by Django 4.2.1 on 2025-01-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_contacts_alter_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='what_doing',
            field=models.CharField(default='', max_length=100, verbose_name='Занятость'),
        ),
    ]
