# Generated by Django 4.2.1 on 2025-01-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='display_on_main',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
