# Generated by Django 4.2.1 on 2025-01-06 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_specialist_display_on_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialists', to='users.category', verbose_name='Направление'),
        ),
    ]
