# Generated by Django 4.2.1 on 2025-01-06 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_specialist_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
    ]
