# Generated by Django 4.2.1 on 2025-01-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistservice',
            name='category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_services', to='users.category', verbose_name='Направление'),
            preserve_default=False,
        ),
    ]
