# Generated by Django 4.2.1 on 2025-01-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_specialistservice_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialistservice',
            name='category',
        ),
    ]
