# Generated by Django 4.2.1 on 2025-01-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, unique=True, verbose_name='Слаг'),
        ),
    ]
