# Generated by Django 4.2.1 on 2025-01-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(help_text='Пример: ул. (Название улицы или проспекта(пр.)), (Номер дома), Город<br>Если в адресе проспект, то надо писать полностью: проспект (Название)', max_length=255, unique=True, verbose_name='Адрес'),
        ),
    ]
