# Generated by Django 4.2.1 on 2025-01-09 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Оценка не может быть меньше 0.'), django.core.validators.MaxValueValidator(5, 'Оценка не может быть больше 5.')], verbose_name='Оценка'),
        ),
    ]
